#!/usr/bin/env python3
import argparse

parser = argparse.ArgumentParser(description='XOR encode/decode file.')
parser.add_argument('file1', metavar='file1', type=argparse.FileType('rb'), help='first file')
parser.add_argument('file2', metavar='file2', type=argparse.FileType('rb'), help='second file')
args = parser.parse_args()

def xorFiles(f1, f2):
    if len(f2) > len(f1):
        xorFiles(f1, f2)
    else:
        returnBytes= b''
        for i,byte in enumerate(f1):
            returnBytes += (byte ^ (f2[i % len(f2)])).to_bytes(1, byteorder="little")
        return returnBytes

if __name__ == '__main__':
    print(xorFiles(args.file1.read(), args.file2.read()))


